### ISSUE TITLE
https://earthview.withgoogle.com is down

### ISSUE THREAD

**Issue by gador** [nicolas-goudry/earth-view#6]
Hi, 
thanks for the cool project! 

I just noticed the [website](https://earthview.withgoogle.com) you reference to is down. According to the way back machine its down for the past few month.
Does it have any impact on your service?

**Comment by nicolas-goudry** [comment]
Hi, thanks for reporting this! I’m aware of that and as a matter of fact the website does work, but on its own schedule :sweat_smile: Sometimes its up, but most of the time it’s just a plain 404.

Be reassured that the assets are not retrieved from this website, so the module isn’t affected. Assets are pulled from gstatic.com, which is a server where Google hosts its static content like CSS, Javascript code and images. Furthermore, these URLs are the same as those used by the [Chrome extension](https://chromewebstore.google.com/detail/earth-view-from-google-ea/bhloflhklmhfpedakmangadcdofhnnoh), so you shouldn’t expect any issues.

I don’t really know what to do about the website, maybe I should just remove the link from the project and add a “website down” in the [acknowledgments section](https://github.com/nicolas-goudry/earth-view/tree/master?tab=readme-ov-file#-acknowledgments) of the readme. Will think about that, since it may frighten potential users.

**Comment by gador** [comment]
Thanks for the explanation! I guess just a "heads up" isn't too bad, since the assets aren't linked to the website
